Fix User participation in Diary
proepidesenvolvimento/guardioes-app pull request #151
Opened 2020-09-02 15:54 UTC by alvesitalo

**Descrição**<br>
Explicar as mudanças feitas nesse pull request, referenciando as issues que foram resolvidas com esse pull request e os responsáveis por ela.<br>
Ex: Foi feito o documento A (#12 - @fulano e @ciclano) para que possamos visualizar melhor o contexto do projeto e modificado o documento B (#28 - @fulano) para atualizar proposta de projeto;<br>

**Checklist**
- [x] Código compila corretamente (Se aplicável);
- [x] Mudanças realizadas foram testadas e passaram no testes (Se aplicável);

2020-09-04 18:49 UTC, RenatoBrittoAraujo requested changes
![image](https://user-images.githubusercontent.com/45462822/92275577-ae645380-eec5-11ea-873e-4811176f38ca.png)

Embora eu ter participações no diário, o gráfico de estatísticas me mostra que 100% dos dias foram não informados.

2020-09-04 19:02 UTC, alvesitalo commented
@RenatoBrittoAraujo A API está retornando o created_at do user (se estiver me fala a data)? Creio que pode ser isso e/ou na hora de abrir o aplicativo o AsyncStorage recebeu nulo.

2020-09-04 20:23 UTC, RenatoBrittoAraujo commented
Vou certificar e edito esse comentário quando tiver a resposta

2020-09-17 16:56 UTC, gabrieldouurado approved these changes

2020-09-17 16:56 UTC, merged