Feature/ci cd
proepidesenvolvimento/guardioes-app pull request #171
Opened 2020-10-19 17:42 UTC by gabiMSilva

# Implementando Integração Contínua

## Contribuição

Gostaria de contribuir com a otimização da pipeline de CI nesse repositório.

## Ferramentas

- **Travis** para executar o pipeline
- **Code Climate** para gerenciamento da manutenibilidade
- **ESLint** para apontamento de erros relacionados à padrão de código no JS  - isso é mostrado no Code Climate - e publicação da cobertura de testes.

## Pipeline

### Quando?
Quando houver Pull Requests e novos commits.

### Onde?
Na develop e master

### O que?
Na branch _development_: executa os testes, publica a cobertura no Code Climate e gera uma release contendo o apk do aplicativo (a parte da release já estava feita no repositório).

Na branch _master_: executa os testes e publica a cobertura no Code Climate.

_Obs.: A nova pipeline foi testada com outras chaves e credenciais a fim de assegurar o seu funcionamento_

- Última build no Travis: [Travis](https://travis-ci.org/github/FGA-GCES/guardioes-app/jobs/737139349)
- Release gerada: [Release - Github](https://github.com/FGA-GCES/guardioes-app/releases/tag/untagged-4bd0ab2412a848f7bcb6)

---

**Para publicar no Code Climate é necessário que um desenvolvedor no repositório adicione o projeto no [Code Climate](https://codeclimate.com/oss/dashboard) e crie uma secret que contenha o Test Coverage ID**

Saiba mais em [Encontrando seu _Test Coverage ID_](https://docs.codeclimate.com/docs/finding-your-test-coverage-token)

_Obs.: Eu comentei um teste genérico que estava dando problema pra não atrasar mais esse PR, mas outra dupla será encarregada de gerar mais testes e isso será resolvido._

2020-11-11 13:22 UTC, alvesitalo commented
Olá @gabiMSilva e @FabianaRibas, ficou muito bom dessa forma. Além de resolver o conflito no arquivo *package-lock.json* eu vou pedir só mais uma modificação no travis que a gente deveria já ter feito antes.

2020-11-11 13:32 UTC, alvesitalo requested changes

2020-11-11 13:32 UTC, alvesitalo commented on .travis.yml
> +  - echo "API_URL=http://gds.proepi.org.br" > .env
Substituir essa linha por:
```echo "API_URL=${API_URL}" > .env```

2020-11-11 13:32 UTC, alvesitalo commented on .travis.yml
> +  - echo "APP_ID=1" >> .env
e essa por:
```echo "APP_ID=${APP_ID}" >> .env```

2020-11-11 15:20 UTC, gabiMSilva commented
@alvesitalo Feito!  =D

2020-11-12 15:18 UTC, alvesitalo approved these changes

2020-11-12 15:21 UTC, merged