Adding households by Profile's page
proepidesenvolvimento/guardioes-app pull request #256
Opened 2021-07-14 20:15 UTC by jps12

**Descrição**<br>
Foi adicionado um botão no header da página de perfis que redireciona para a página de adicionar um novo perfil. Depois de adicionar o usuário vai ser redirecionado para a página home.

**Checklist**
- [x] Código compila corretamente (Se aplicável);
- [ ] Mudanças realizadas foram testadas e passaram no testes (Se aplicável);
- [ ] Documentos gerados/atualizados (Se aplicável);
- [ ] Feito por conta própria (Se aplicável).

2021-07-15 17:29 UTC, alvesitalo requested changes
Deixei alguns comentários no código

2021-07-15 17:29 UTC, alvesitalo commented on src/api/households.js
> -        console.log(err)
Essa parte aqui acho que você pode manter da forma que tava, todas as requests estão padronizadas dessa forma pra verificação de erros.

2021-07-15 17:29 UTC, alvesitalo commented on src/navigation/AppStack.js
> +                                    {scene.descriptor.options.rightButton !== undefined?
Aqui quando abro no VSCode, a extensão do Prettier mostra que indentação ta incorreta. Era bom usar o ESLint + Prettier pra manter o código sempre com o mesmo padrão de indentação.

2021-07-16 14:53 UTC, jps12 commented on src/navigation/AppStack.js
> +                                    {scene.descriptor.options.rightButton !== undefined?
Ok, vou usar a extensão Prettier ESLint e formatar por ela.

2021-07-16 19:45 UTC, alvesitalo approved these changes

2021-07-16 19:45 UTC, merged