BUG de embaralhamento do seletor de instituições.
proepidesenvolvimento/guardioes-app pull request #262
Opened 2021-08-10 02:18 UTC by jps12

**Descrição**<br>
O bug foi reproduzido quando uma pessoa já é cadastrada ai ela muda dois campos: o primeiro e o filho desse primeiro, e sai da página de editar perfil sem salvar. Para corrigir isso foi apagado todo o estado armazenado assim que o usuário sai da página. 

**Checklist**
- [x] Código compila corretamente (Se aplicável);
- [ ] Mudanças realizadas foram testadas e passaram no testes (Se aplicável);
- [ ] Documentos gerados/atualizados (Se aplicável);
- [x] Feito por conta própria (Se aplicável).

2021-08-11 18:28 UTC, alvesitalo requested changes
O componente ainda ta embaralhando os grupos quando um usuário já possui uma Instituição. 

![Screenshot_20210811-125249](https://user-images.githubusercontent.com/35741521/129083143-dbb2d4b3-7cff-4832-944c-753acc5dcfa2.png)

Creio que o problema esteja na linha 218 `await this.getChildren(group.id, false)` quando o loop busca os grupos filhos na API. Verificar por que o await não ta sendo respeitado.

2021-08-11 18:28 UTC, alvesitalo commented on src/components/Groups/InstitutionSelector.js
> -        }
Essa validação de possuir um grupo antes de salvar o perfil é importante para o usuário não tentar salvar uma seleção incompleta como Instituição. É melhor manter ela.

2021-08-11 18:28 UTC, alvesitalo commented on src/components/Groups/InstitutionSelector.js
> -                                    ...this.state.selectionIndexes.slice(index + 1),
Verificar se essa mudança não causa problema no comportamento do componente.

2021-08-11 18:39 UTC, jps12 commented on src/components/Groups/InstitutionSelector.js
>          if (doesTheSelectedGroupRequireID && isIdPresentIfNeeded) {
Entendi

2021-08-11 18:40 UTC, jps12 commented on src/components/Groups/InstitutionSelector.js
>              isIdPresentIfNeeded &&
Entendido

2021-08-11 18:42 UTC, jps12 commented on src/components/Groups/InstitutionSelector.js
> -                                    ...this.state.selectionIndexes.slice(index + 1),
Então ela na vdd ajudou, pq antes quando o usuário tinha cadastrado a instituição e por exemplo ia alterar o estado, o campo seguinte ficava com o valor antigo. Com esse campo zerado e aparece "Select" no label em vez do valor antigo, o
 app funcionou normalmente nos testes que eu fiz.

2021-08-14 03:22 UTC, jps12 commented on src/components/Groups/InstitutionSelector.js
> +    }
Isso foi retirado...

2021-08-14 03:22 UTC, jps12 commented on src/components/Groups/InstitutionSelector.js
>          if (doesTheSelectedGroupRequireID && isIdPresentIfNeeded) {
Foi recolocado os comentários

2021-08-14 03:32 UTC, jps12 commented
Bem eu fiz mais algumas alterações. Ao que parece o app ta fazendo as requisições de modo assincrono e por isso a array ficava embalharada. Eu coloquei alguns awaits e async para esperar as requisições so que demorava bastante (e surgia cada vez mais bugs). 
Por isso decidi trabalhar com ordenação, pois assim conseguimos tirar provei dessa "paralelização" e procurei algumas estururas de dados auto-ordenadas (tipo rb tree) e tbm algoritmos de ordenação. 
Eu escolhi o insertion sort porque, apesar da inserção ser em O(n), a leitura também é. Enquanto  estruturas auto-ordenada tem inserção mais rápida enquanto a leitura é mais devagar e como o app renderiza várias vezes, e para cada vez a array é lida de novo decidi pelo insertion sort. Outro ponto seria que uma rb tree teria que ser implementada na mão.

2021-08-16 12:31 UTC, alvesitalo approved these changes
Boa solução @jps12

2021-08-16 12:32 UTC, merged