Feature/user categorization
ProEpiDesenvolvimento/guardioes-app pull request #271
Opened 2021-12-19 22:41 UTC by EduardoMdR

**Descrição**<br>
Nesse PR foi adicionado a funcionalidade de um usuário poder adicionar uma categoria (quando acessa a página 'EditarPerfil')
Deve ser testado com a api <a href="https://github.com/ProEpiDesenvolvimento/guardioes-api/pull/367"> Feature/user categorization #367 </a> caso ainda não tenha acontecido o merge na development.
<br>

**Observação**<br>
Por causa problemas referente ao meu ambiente de programação, alguns erros podem acontecer (por isso a review para ter uma visão de fora)
Ainda é preciso adicionar um Select no lugar de um Input normal (referente ao campo da categoria em 'EditarPerfil'), mas também resolvi esperar a review.
<br>

**Checklist**
- [ ] Código compila corretamente (Se aplicável);
- [ ] Mudanças realizadas foram testadas e passaram no testes (Se aplicável);
- [ ] Documentos gerados/atualizados (Se aplicável);
- [ ] Feito por conta própria (Se aplicável).

2021-12-23 00:40 UTC, robsonramon commented on src/screens/principal/EditarPerfil/index.js
> +
A adição do campo de categoria está funcionando conforme o esperado. Basicamente falta substituir o Input simples por um select, assim como mencionado no PR.

2021-12-23 01:03 UTC, alvesitalo commented on src/screens/principal/EditarPerfil/index.js
> +
Basicamente é criar um arquivo categories.js em `src/api` para se fazer a requisição na API e também é necessário adicionar o Autocomplete (Select) no Cadastro e em Adicionar Perfil.

2022-01-14 17:22 UTC, robsonramon requested changes

2022-01-14 17:22 UTC, robsonramon commented on src/screens/inicio/Register/index.js
> +                                initValue={translate('selector.label')}
Ficou muito bom, só acrescentaria o valor inicial da categoria do usuário caso ele já estivesse alocado em uma categoria.

2022-01-14 18:13 UTC, robsonramon approved these changes

2022-01-15 00:48 UTC, alvesitalo requested changes
Pessoal, nos testes o usuário e o household não estão sendo criados com o category_id. Para editar perfil não está mostrando a categoria que o usuário já tinha selecionado também.

2022-01-15 00:59 UTC, alvesitalo commented on src/screens/principal/EditarPerfil/index.js
> +                    description
Esse atributo description não é necessário

2022-01-19 17:45 UTC, EduardoMdR commented
@alvesitalo e @robsonramon , as mudanças solicitadas ja foram implementadas

2022-01-21 16:16 UTC, alvesitalo approved these changes
Corrigi alguns detalhes na edição e nas requisição, tudo funcionando agora 😄

2022-01-21 16:17 UTC, merged