Melhora os feedback nas requisições do aplicativo e  adiciona ping di…
ProEpiDesenvolvimento/guardioes-app pull request #272
Opened 2021-12-23 15:07 UTC by AnaBeatrizPontes

…retamente no servidor do GDS (no hook de User)

**Descrição**<br>
Foi implementado feedback nas requisições do aplicativo e também ping diretamente no servidor do GDS para verificar se está offline (no hook de User).

**Checklist**
- [ ] Código compila corretamente (Se aplicável);
- [ ] Mudanças realizadas foram testadas e passaram no testes (Se aplicável);
- [ ] Documentos gerados/atualizados (Se aplicável);
- [ ] Feito por conta própria (Se aplicável).

2021-12-27 19:17 UTC, alvesitalo commented on package.json
> +    "react-native": "^0.66.1",
Volte pra versão 0.64.1, depois abrimos uma issue para atualizar todas as bibliotecas.

2021-12-27 19:45 UTC, alvesitalo commented on src/hooks/user.js
> +		const pingServer = async (ip, callback) => {
Não consegui compreender a utilidade dessa função, não utilizar `this` também porque esse componente é funcional.

2021-12-27 19:56 UTC, alvesitalo requested changes
Oi Ana, a sua solução atual não resolve o problema 😢 . A ideia era utilizar [essa configuração](https://github.com/react-native-netinfo/react-native-netinfo#configure) da biblioteca NetInfo que a gente já utiliza, para o ping se fosse possível. E adicionar o timeout automaticamente em todas as requisições que utilizam fetch() ou utilizar outra biblioteca como o Axios para fazer isso.

2021-12-27 19:56 UTC, alvesitalo commented on src/hooks/user.js
> +				this.inUse = true;
Não utilizar this porque esse componente é funcional.

2022-01-18 17:57 UTC, robsonramon approved these changes

2022-01-19 20:40 UTC, alvesitalo approved these changes

2022-01-21 14:28 UTC, merged